### ISSUE TITLE
Release v0.1.24

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/generator-theia-extension#108]
@vince-fugnitto 
Do you think it would be possible to push a new release due to https://github.com/eclipse-theia/generator-theia-extension/issues/105

**Comment by vince-fugnitto** [comment]
@JonasHelming sure, it would be good since new versions of the `tree-editor` are likely broken :+1:

**Comment by vince-fugnitto** [comment]
@JonasHelming can you confirm the new version works for you? (`0.1.24`): 
- https://www.npmjs.com/package/generator-theia-extension

**Comment by JonasHelming** [comment]
Works well for me, thank you!

**Comment by vince-fugnitto** [comment]
> Works well for me, thank you!
