### ISSUE TITLE
docs: generated readme includes outdated information

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/generator-theia-extension#109]
The generated `readme.md` includes outdated information regarding the **node** version.

- https://github.com/eclipse-theia/generator-theia-extension/blob/master/templates/README.md

We should align the version with the expectations from the framework, or directly reference the link to the framework's prerequisites:

- https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites

In addition, we should add a `engines` property to the `package.json` to fail the build if the node and yarn version are incorrect:

- https://github.com/eclipse-theia/theia/blob/9b9cc2ba4864a45edcb34b459485d8aa54268a5d/package.json#L5-L8

**Comment by roxanadangerm** [comment]
Hi @vince-fugnitto ,
Could you please, provide the updated information? I am trying to test theia examples, and I am getting errors.
I am using the Dockerfile:```

FROM node:14

RUN apt-get update \
    && apt-get install -y build-essential gcc make python3 pkg-config  libx11-dev libxkbfile-dev libsecret-1-dev \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# install code generator for theia extensions
RUN npm install -g yo generator-theia-extension

USER node

EXPOSE 3000

CMD sleep infinity
```
and then inside the container:

`yo theia-extension`

But, I get the following errors:

warning Error running install script for optional dependency: "/workspaces/theia-dev/tree/node_modules/msgpackr-extract: Command failed.
Exit code: 126
Command: node-gyp-build-optional-packages
Arguments:
Directory: /workspaces/theia-dev/tree/node_modules/msgpackr-extract
Output:
[10/11] ⡀ lzma-native[8/11] ⡀ node-pty
[9/11] ⡀ @theia/ffmpeg[6/11] ⡀ electron
error /workspaces/theia-dev/tree/node_modules/lzma-native: Command failed.
Exit code: 126
Command: node-gyp-build
Arguments:
Directory: /workspaces/theia-dev/tree/node_modules/lzma-native`

Could anyone help me to understand what I am doing incorrect?

I have also tested with node:16.15.1, but it didn't solved either.

Many thanks!

**Comment by vince-fugnitto** [comment]
@roxanadangerm the updated documentation should simply point to the framework's [prerequisites](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites) so you can take a look there for now. 

I'm not sure that the generator within the dockerfile is a good idea, the generate scaffolds a project with `electron` + `browser` + a custom extension where you can provide customizations. The `electron` application is not something you'd be able to run in your dockerfile, so you'd have to target the browser example only.

**Comment by roxanadangerm** [comment]
Many thanks @vince-fugnitto. My Dockerfile actually comply with the prerequisites. 

wrt Dockerfile, Is there any alternative where I can isolate the resources/packages used in the theia extensions?

**Comment by vince-fugnitto** [comment]
> * labelprovider does not change the icon. In fact it oes not call the getIcon() method.

The `labelProvider` relies on a file-icon theme being set and will update the icon (star):

![image](https://user-images.githubusercontent.com/40359487/196434362-db30c9ea-a6bf-4951-a8ee-dd16fa7282a7.png)

**Comment by roxanadangerm** [comment]
I got it!!
Thank you!
