### ISSUE TITLE
root ERROR Child node 'open-editors:root' does not belong to this 'open-editors:root' tree.

### ISSUE THREAD

**Issue by paulfrench** [eclipse-theia/generator-theia-extension#120]
### Bug Description:
When trying to run the editor demo I get error...

root ERROR Child node 'open-editors:root' does not belong to this 'open-editors:root' tree.

### Steps to Reproduce:

1. Follow instructions here https://eclipsesource.com/blogs/2021/02/03/how-to-build-a-tree-editor-in-eclipse-theia/
2. After "yarn start" and going to http://localhost:3000/ I get error as in title of this issue
3. The Tree Editor menu is visible but there is no example file menu under it, it is an empty menu

### Additional Information

- Operating System:  windows 10 profiessional, chrome or edge browser 
- Theia Version: latest as of 18th Oct 2021

**Comment by JonasHelming** [comment]
@lucas-koehler

**Comment by paulfrench** [comment]
Thanks - all good
