### ISSUE TITLE
`yo theia-extension` runs and does nothing for some minutes

### ISSUE THREAD

**Issue by kkistm** [eclipse-theia/generator-theia-extension#131]
Running `yo theia-extension` produces 2-4 minutes pause before something is started to be shown. Most likely some network/proxy issues in the company network, but other tools which access the network responds quickly.

**Comment by JonasHelming** [comment]
@kkistm does this still occur?

**Comment by kkistm** [comment]
I've checked with `yeoman@4.3.1`, it looks like the problem disappeared. `yo theia-extension` answers quite quickly, in a matter of seconds.
