### ISSUE TITLE
How to call the Theia API?

### ISSUE THREAD

**Issue by dabm-git** [eclipse-theia/generator-theia-extension#143]
Not the best place to ask, but, how to get e.g: the names of open files, if they are modified, if the user is using a git tool, the number of changes of the git branch....?

**Comment by vince-fugnitto** [comment]
> Not the best place to ask

@dabm-git thank you for the issue, I would suggest creating a [github discussion](https://github.com/eclipse-theia/theia/discussions) or a post on the [forum](https://community.theia-ide.org/) instead, where other questions are asked.

>  the names of open files

Using the [`@theia/editor`](https://www.npmjs.com/package/@theia/editor) dependency, you'll have access to the [`EditorManager`](https://eclipse-theia.github.io/theia/docs/next/classes/editor.EditorManager-1.html) which knows about all opened editors (using `.all`).

```ts
@inject(EditorManager)
protected readonly editorManager: EditorManager;

getFilenames(): string[] {
  const editors = this.editorManager.all;
  ....
}
```

>  the user is using a git tool, the number of changes of the git branch

You'll probably want to take a look at the [`@theia/scm`](https://www.npmjs.com/package/@theia/scm) dependency.
