### ISSUE TITLE
widget does not position in the default area 

### ISSUE THREAD

**Issue by roxanadangerm** [eclipse-theia/generator-theia-extension#161]
Hello,
I am testing the widget example and I am trying to customise a widget to set it up in the top area. I changed the value of the default location of the widget with: 

`defaultWidgetOptions: { area: 'top' },`

in the file widget-contibution.ts.

But, I can not see a change of the widget position. It does not work for other values either.

What other changes I need to do for achieving this behaivour?

Many thanks!

**Comment by vince-fugnitto** [comment]
@roxanadangerm I believe the `top` panel is pretty specific to what can be rendered there, currently it is the main menu, do you maybe mean the `main` area? 

If you're modifying the layout of the application you may want to execute the `reset workbench layout` command which will clear any previous layout data stored in local-storage. This may explain why despite updating your area in the code you are still loading the older data which gets saved when a user exists the app.

**Comment by roxanadangerm** [comment]
Great, the reset command did the trick!
Thank you very much @vince-fugnitto !
