### ISSUE TITLE
widget menu click error

### ISSUE THREAD

**Issue by gouych** [eclipse-theia/generator-theia-extension#168]
I created a base project with scaffolding using the widget option, and this was created successfully. But when I click the registered menu under view, it always prompts an error: "You are attempting to construct 'class MyWidget' in a synchronous way but it has asynchronous dependencies.

**Comment by gouych** [comment]
[
![image](https://github.com/eclipse-theia/generator-theia-extension/assets/43327905/8f9b69aa-f011-48dc-99f6-844fdaa27549)
](url)

**Comment by JonasHelming** [comment]
Could you check which Theia version are you building against? You see this for example in the /browser-app/package.json

**Comment by msujew** [comment]
@JonasHelming This is an issue I've encountered multiple times during my inversify update PR. We should change [here](https://github.com/eclipse-theia/generator-theia-extension/blob/a23c6e22c237afae2a859360530f98d72127dfaf/templates/widget/widget.tsx#L17-L25):

```diff
-    @postConstruct()
-    protected async init(): Promise < void> {
-        this.id = <%= params.extensionPrefix %>Widget.ID;
-        this.title.label = <%= params.extensionPrefix %>Widget.LABEL;
-        this.title.caption = <%= params.extensionPrefix %>Widget.LABEL;
-        this.title.closable = true;
-        this.title.iconClass = 'fa fa-window-maximize'; // example widget icon.
-        this.update();
-    }
+    @postConstruct()
+    protected init(): void {
+        this.doInit();
+    }
+
+    protected async doInit(): Promise <void> {
+        this.id = <%= params.extensionPrefix %>Widget.ID;
+        this.title.label = <%= params.extensionPrefix %>Widget.LABEL;
+        this.title.caption = <%= params.extensionPrefix %>Widget.LABEL;
+        this.title.closable = true;
+        this.title.iconClass = 'fa fa-window-maximize'; // example widget icon.
+        this.update();
+    }
```

**Comment by gouych** [comment]
The version is: "@theia/core": "latest", others are the latest.
msujew's answer successfully solved my problem. thank you all
