### ISSUE TITLE
Need for a theia clean or build:clean

### ISSUE THREAD

**Issue by mgerzabek** [eclipse-theia/generator-theia-extension#180]
Is there something like a `yarn build:clean` or `theia clean` that deletes all built artefacts?

When I develop without `yarn watch`, do a `yarn build:browser` and restart theia the changes are not picked up. But when I delete all lib folders and do the rebuild then the changes are picked up.

What am I missing?

**Comment by vince-fugnitto** [comment]
@mgerzabek you can run the `yarn theia clean` command from packages you wish to cleanup. 
If you are not using the `yarn watch` workflow, then you should rebuild packages that have been modified, rebuild the example application(s) and restart.

**Comment by JonasHelming** [comment]
@mgerzabek Is this solved?

**Comment by mgerzabek** [comment]
Sorry, forgot to close… thnx!
