### ISSUE TITLE
run "yo theia-extension" Error theia-extension

### ISSUE THREAD

**Issue by CaGeek** [eclipse-theia/generator-theia-extension#182]
![1700117172373](https://github.com/eclipse-theia/generator-theia-extension/assets/22286262/d5cc51a8-80f5-431d-8cae-3590cabf3e78)

**Comment by JonasHelming** [comment]
Thank you for the report. Which "yo" version do you have installed?

**Comment by CaGeek** [comment]
@JonasHelming yo 5.0.0 version

**Comment by jcanchen** [comment]
npm install yo@4.0.0 -g
this may work

**Comment by JonasHelming** [comment]
Yes, could you try this? Yeoman 5.0 was release 2 days ago, there might be incompatibilities.

**Comment by JonasHelming** [comment]
4.3.1 works well for me

**Comment by jcanchen** [comment]
It should work. Been tested yesterday.

**Comment by CaGeek** [comment]
@jcanchen @JonasHelming  right  thanks！

**Comment by JonasHelming** [comment]
@CaGeek Could you confirm that the new version fixes the issue with yo 5.0.0?
