### ISSUE TITLE
 yo theia-extension hello-world-extension,  permission denied,

### ISSUE THREAD

**Issue by cwy57885142** [eclipse-theia/generator-theia-extension#197]
root@k8s01:~/cwy/my-extension# yo theia-extension hello-world-extension
? The extension's type Hello World
HelloWorldExtension
   create package.json
Error theia-extension hello-world-extension

EACCES: permission denied, open '/root/cwy/my-extension/package.json'
┌───────────────────────────────────────────────────┐
│              yo update check failed               │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘

1、Why does this step prompt no permission, I have been looking for a long time have not found the reason

**Comment by msujew** [comment]
Hey @cwy57885142,

I'm not conpletely sure, but this looks like a yeoman issue, not an issue on our end.

Habe you tried running the yeoman generator in a different directory outside of `root`?

**Comment by JonasHelming** [comment]
closing, as no response to the question. Please feel free to reopen if the issue persists.
