### ISSUE TITLE
Dependency Versions

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/generator-theia-extension#221]
In the generated app `package.json`s, the Theia dependecies are listed with `latest` version. I don't think this makes a lot of sense: At the same time, we have other dependencies which are fixed, like `"electron": "^30.1.2"`. There is a good chance, these dependencies will start to clash at one point. IMO, we should use the Theia version number that is current at the time of generating the app. That is also best practice for real Theia applications, so will serve as a good example.

**Comment by JonasHelming** [comment]
There is a parameter to set the Theia version see #119 
But we should still decide what to use as a default

**Comment by tsmaeder** [comment]
I think the current version at the time of generation is a good default. We'd have to find out what that is, but we should be able to find out via npm.
