### ISSUE TITLE
Integrating a generated extension into theia cloud

### ISSUE THREAD

**Issue by NickLagogiannis** [eclipse-theia/generator-theia-extension#235]
Greetings,

In our company, we are trying to integrate an extension produced by yeoman generator, specifically "Tree Editor".
Following the documentation [https://theia-ide.org/docs/composing_applications](url) we successfully created our extension and used the "yarn package" to export it as a tgz file to use it elsewhere.

Our goal is to integrate it into our Theia IDE for cloud application, which we installed on our azure cloud by following the documentation [https://github.com/eclipse-theia/theia-cloud/blob/azure-documentation/doc/docs/platforms/Azure.md](url) and its working, but we can't find any instructions about adding an extension to it. Therefore we followed the following path : 

First, we ensured that our extension is working:

We have downloaded locally also a version of Theia IDE for desktop and added the "Tree Editor" extension in the package.json and it's working properly.

Second, we created a docker image by using the "browser.Dockerfile". Specifically, we edit package.json in the "./theia-extensions/product" folder to include our "Tree Editor" extension, create an image using the "browser.Dockerfile," and run a container with that image, which is also working properly.

We tried to use the same strategy by creating an image of landing-page with dockerfile.local that contains also our extension, push it on a private registry, and then replacing the original image from valuesAzure.yaml 
![modified_image](https://github.com/user-attachments/assets/07fec33b-509a-4069-8336-67966086ed80)
![original_image](https://github.com/user-attachments/assets/4da78d80-5b28-447f-9c2e-01e776c9a25d)
We reinstalled our Theia IDE for cloud application and even though we do not have any error in this procedure, the extension does not appear when we start the Theia IDE in the cloud. 

Can you give us a hint how to proceed?
Did we do something wrong in the path we followed or is there another recommended procedure to integrate an extension to the Theia Cloud IDE?

**Comment by sgraband** [comment]
Hey @NickLagogiannis ,

You're correct that the extension needs to be added to the package.json of your Theia application. This application then needs to be transformed into a Docker image. For reference, you can check these examples: [theia-cloud-demo](https://github.com/eclipse-theia/theia-cloud/tree/main/demo/dockerfiles/demo-theia-docker), [monitor-extension example](https://github.com/eclipse-theia/theia-cloud/tree/main/demo/dockerfiles/demo-theia-monitor-theia), and [theia-ide](https://github.com/eclipse-theia/theia-ide/blob/master/browser.Dockerfile).

This Docker image should then be the one you reference in your app definition. The landing page is unrelated to this process. To learn more about app definitions and adding your application to theia cloud, you may find these guides helpful: [Add your Application](https://theia-cloud.io/documentation/addapplication/) & [Theia Cloud Overview](https://theia-cloud.io/documentation/overview/).

Let me know if you have any questions about that.
