### ISSUE TITLE
proposal: Re-license repository, move it repository under 'eclipse-theia'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/generator-theia-extension#60]
**Description**

The proposal is to move the repository under the [eclipse-theia](https://github.com/eclipse-theia) organization. Moving the repository can potentially increase visibility and also welcome additional contributions and contributors.  One issue with moving might be re-licensing the repository.

Would anyone object to moving the repo?

cc @marcdumais-work @svenefftinge @akosyakov

**Comment by akosyakov** [comment]
It sounds fine with me. There was also this issue: https://github.com/eclipse-theia/theia/issues/7387 to reduce maintenance. Another thing to consider it could be worth to turn it into application generator so we can support different layouts, i.e. developing VS Code extension against Theia, Theia extension, mix of them or just generate an app for one of platforms. Right now it is not easy to setup.

**Comment by JonasHelming** [comment]
About the "developing VS Code extension against Theia": I totally like this idea, and I would be happy to contribute that. However, we should not forget about: https://github.com/eclipse/theia-generator-plugin

So the VS Code extension template would rather fit into the plugin generator, wouldn't it? Or maybe, we even want to merge the two generators mid-term?

**Comment by marcdumais-work** [comment]
cc: @benoitf

**Comment by benoitf** [comment]
repository theia-generator-plugin and theia-plugin-packager can be moved from `eclipse` to `eclipse-theia`

**Comment by marcdumais-work** [comment]
One thing to keep in mind is that we will need to re-license this repo before the move, from Apache 2 to probably EPL 2. We've done the [same for the main repo](https://github.com/eclipse-theia/theia/wiki/Theia-Re-Licensing) a while ago and it's not necessarily easy: we need to get permission from every contributor or copyright holder when not the same. If not possible for some of the commits, the alternative is to remove them. 

Other than the "usual suspects" I see a few contributor's names I do not immediately recognize:
https://github.com/theia-ide/generator-theia-extension/graphs/contributors

**Comment by JonasHelming** [comment]
I obviously agree to the re-licensing, The Zoker will (he is affiliated with us), therrance only changed a version number (we could revert if he does not agree) and vazexqi change a tsconfig file (same)

**Comment by marcdumais-work** [comment]
> I obviously agree to the re-licensing, The Zoker will (he is affiliated with us), therrance only changed a version number (we could revert if he does not agree) and vazexqi change a tsconfig file (same)

Thanks Jonas for having a closer look - re-licensing may not be so hard after all. Note however that in some cases like for Vince and myself, our employer is the copyright owner of our contributions and we'll need to escalate internally to obtain such a permission officially. It could be the case for others as well. Still, this is not an insurmountable obstacle.

**Comment by JonasHelming** [comment]
Perfectly understood, I am personally authorized to give this permission for me and the Zoker

**Comment by marcdumais-work** [comment]
> So the VS Code extension template would rather fit into the plugin generator, wouldn't it? 

@benoitf would you welcome this contribution? 

> repositories theia-generator-plugin and theia-plugin-packager can be moved from `eclipse` to `eclipse-theia`

I understand you would be in favor of merging the two genarator?

**Comment by benoitf** [comment]
@marcdumais-work well when we started the plugin generator we asked if we could add it to the extension generator and it was decided that it was not a good way to mix two concepts...

Also it's not interesting to have the extension generator when you're on a running Theia as you can't add any extension at runtime so I'm unsure it's a good way to merge them.

**Comment by marcdumais-work** [comment]
> @marcdumais-work well when we started the plugin generator we asked if we could add it to the extension generator and it was decided that it was not a good way to mix two concepts...
> 
> Also it's not interesting to have the extension generator when you're on a running Theia as you can't add any extension at runtime so I'm unsure it's a good way to merge them.

Ok, makes sense, thanks @benoitf . So probably merging the two generator together may not be so useful or at least debatable. 

What about a having the VS Code extension template contributed to the plugin generator, as proposed by @JonasHelming?

**Comment by benoitf** [comment]
> What about a having the VS Code extension template contributed to the plugin generator, as proposed by @JonasHelming?

@marcdumais-work it may be cool but I'm not sure to see the benefits ?
Like using .theia packaging but with VS Code api ? or generating vsix files with VS Code API ? in that case, what are the difference with VS Code generator ?

BTW if we have several generators, yeoman is prompting you which one you want to pickup.

**Comment by JonasHelming** [comment]
To avoid any misunderstandings: The VS Code extension template was proposed by @akosyakov (although I like the idea). I proposed to put it into the plugin generator rather than here. 
So maybe @akosyakov can give feedback to your questions.

**Comment by benoitf** [comment]
I would like to have an example on having VS Code extension with using both Theia and VS Code and other namespaces but IMHO it's not yet possible. (As we change the target namespace for now)

**Comment by akosyakov** [comment]
For our customers we have setups with Theia + VS Code extensions, i.e. VS Code extensions bring language and debug support, Theia extensions restyle, rebrand UI brings new views, they communicate via generic commands. VS Code extensions then used in VS Code with limited functionality. As soon as we drop the monaco-languageclient, such setups will be normal. I have not seen in practice Theia plugins besides in Che.

We could also think about composing different generators: https://yeoman.io/authoring/composability.html

**Comment by JonasHelming** [comment]
OK, let us summerize the discussion above, I think there are the followng proposals:
1. Move this repo under eclipse-theia
2. Move the content into the main repo (eclipse-theia/theia#7387)
3. Merge extension and plugin generator or combine using composition
4. Provide a new VS Code like template

I think there is agreement on "1." and that is what this issue is actually about, so I think it makes sense to do this first. So is there something to help with to complete 1.?

**Comment by JonasHelming** [comment]
Any news on this? Again please let me know, if I can assist you with anything...

**Comment by marcdumais-work** [comment]
Hi @JonasHelming ,

As discussed offline we'll go ahead with step one  for the 3 repos, or let's say step 0.5 - Sharon confirmed we'll need to re-license each repo first, to match the Eclipse Theia license. I'm hoping you can help with getting contributors permissions and potentially removing/replacing contributions we can't re-license, for this repo and `theia-ide/theia-website`. I'll take care of `theia-ide/vscode-builtin-extensions`, that I added to the list :)

I am working on documenting each of the 3 repo's contributions and sorting-out who we need to get permission-from. 
It should not be too bad. I'll add a "re-licensing" or such page on each repo with this info, shortly. 

Ref: 
- https://github.com/theia-ide/vscode-builtin-extensions/issues/16
- https://github.com/theia-ide/theia-website/issues/122

**Comment by JonasHelming** [comment]
Hi @marcdumais-work ,

yes I can certainly do that. Please ping me, when the document is in place (you can probably use https://github.com/eclipse-theia/theia/wiki/Theia-Re-Licensing) as a template.

**Comment by marcdumais-work** [comment]
Hi @JonasHelming ,

I created a wiki to track the re-licensing of this repo:  https://github.com/theia-ide/generator-theia-extension/wiki/Re-licensing-theia-ide-generator-theia-extension

I created one as well for `theia-website`: https://github.com/theia-ide/theia-website/wiki/Re-licensing-theia-ide-theia-website

Please feel free to double-check that I have not missed any contribution or made mistakes. I will contact you by email to discuss how the permissions should be obtained.

**Comment by richardfontana** [comment]
@marcdumais-work I'm a Red Hat lawyer with responsibility for open source - Red Hat authorizes relicensing any Red Hat contributions in [this repo](https://github.com/theia-ide/generator-theia-extension/wiki/Re-licensing-theia-ide-generator-theia-extension) and [theia-website](https://github.com/theia-ide/theia-website/wiki/Re-licensing-theia-ide-theia-website) to EPL 2.0. (As far as I can tell from this comment thread that is the desired license change.)

**Comment by richardfontana** [comment]
@marcdumais-work Sure, you can use rfontana@redhat.com.

**Comment by JonasHelming** [comment]
Update: All individuals agreed (updated in the wiki)

**Comment by JonasHelming** [comment]
I think all permissions are granted by now (https://github.com/theia-ide/generator-theia-extension/wiki/Re-licensing-theia-ide-generator-theia-extension)

**Comment by marcdumais-work** [comment]
Hi @richardfontana , @benoitf ,

Our re-licensing email discussion has stalled, when it was so close to being finalised. We'd like to go forward with the move, and the foundation is asking whether we can remove Red Hat's related commits to unblock the exercise, which we would rather not do (whether it contain IP or not, documentation is useful). Maybe we can quickly wrap this up to everyone's satisfaction?

**Comment by vince-fugnitto** [comment]
Re-licensing seems to now be completed, the latest status presented in the wiki (https://github.com/eclipse-theia/theia/issues/8999) is **done**. I believe it is fine to close the issue @marcdumais-work ?

**Comment by marcdumais-work** [comment]
The repo has moved to the `eclipse-theia` GH org (automatic redirect for the old URL): 
https://github.com/eclipse-theia/generator-theia-extension

There may things the Foundation asks us to do following the move (the CQ I think is still under analysis), but we're done for this issue here.
