### ISSUE TITLE
Publish version v0.1.22

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/generator-theia-extension#92]
@vince-fugnitto Could we maybe publish a new version?

**Comment by vince-fugnitto** [comment]
@JonasHelming do you think we should aim to include more features for the release (is there anything else you'd like to add)?
At the moment, the only updates we had since the last release are some documentation updates, and improved configurations.

**Comment by JonasHelming** [comment]
I am thinking about this one actually: https://github.com/eclipse-theia/generator-theia-extension/pull/89

However, I cannot judge how much effort it is to push a new version. I agree there are not many changes, but one breaking

**Comment by vince-fugnitto** [comment]
@JonasHelming can you confirm that the `0.1.22` release works correctly?

**Comment by JonasHelming** [comment]
@vince-fugnitto : I tested all templates and found one blocker: https://github.com/eclipse-theia/generator-theia-extension/pull/94
All other templates work correctly. Next time, I should do this test before you create the release, sorry...

**Comment by JonasHelming** [comment]
https://github.com/eclipse-theia/generator-theia-extension/pull/94
is merged

**Comment by vince-fugnitto** [comment]
@JonasHelming did you want me to release a new version?

**Comment by JonasHelming** [comment]
yes, please, we have two blocker bugs fixed

**Comment by vince-fugnitto** [comment]
> yes, please, we have two blocker bugs fixed

Version `0.1.23` is released :+1:

**Comment by vince-fugnitto** [comment]
I believe the issue can be closed with `0.1.23` released with the updates we made.
Thank you for your help @JonasHelming.
