### ISSUE TITLE
Add build step to compile all templates

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/generator-theia-extension#95]
We should create and build a templates in the regular build to test, whether they at least compile.
We could add a shell script that creates all extensions (they are then also automatically built)
@vince-fugnitto WDYT?

**Comment by vince-fugnitto** [comment]
@JonasHelming I think its a good idea to determine if the different templates build, ultimately we can:
- add a github actions workflow to build all templates (making sure they compile) on pull-request and possibly a cron job

**Comment by JonasHelming** [comment]
Yes, I will write a shell script, they can be embedded into Github actions
